// IDEA: Las personas tienen los campos: nombre, foto (url), sexo (M/F), pais y nacimiento (dd/mm/yyyy);
// Datos generados por: https://www.mockaroo.com/

const PERSONAS = [
  {"nombre":"Crista","foto":"https://robohash.org/laudantiumvoluptatemut.png?size=50x50&set=set1","sexo":"F","pais":"Russia","nacimiento":"13/02/1970"},
  {"nombre":"Robert","foto":"https://robohash.org/estvelillum.png?size=50x50&set=set1","sexo":"M","pais":"Russia","nacimiento":"20/03/1962"},
  {"nombre":"Pepi","foto":"https://robohash.org/etquiaut.png?size=50x50&set=set1","sexo":"F","pais":"Russia","nacimiento":"16/11/1938"},
  {"nombre":"Roze","foto":"https://robohash.org/ipsumnobisat.png?size=50x50&set=set1","sexo":"F","pais":"Norway","nacimiento":"10/02/1938"},
  {"nombre":"Kerrin","foto":"https://robohash.org/etestenim.png?size=50x50&set=set1","sexo":"F","pais":"Indonesia","nacimiento":"13/09/1977"},
  {"nombre":"Gussie","foto":"https://robohash.org/debitisestconsequatur.png?size=50x50&set=set1","sexo":"F","pais":"Ukraine","nacimiento":"22/11/1940"},
  {"nombre":"Nickie","foto":"https://robohash.org/nonquodin.png?size=50x50&set=set1","sexo":"M","pais":"Mongolia","nacimiento":"06/04/1948"},
  {"nombre":"Demetrius","foto":"https://robohash.org/laboredoloremnihil.png?size=50x50&set=set1","sexo":"M","pais":"Thailand","nacimiento":"11/03/1955"},
  {"nombre":"Reynolds","foto":"https://robohash.org/reprehenderitrerumet.png?size=50x50&set=set1","sexo":"M","pais":"Finland","nacimiento":"20/05/1946"},
  {"nombre":"Ring","foto":"https://robohash.org/aliasautest.png?size=50x50&set=set1","sexo":"M","pais":"France","nacimiento":"03/10/1960"},
  {"nombre":"Sigismundo","foto":"https://robohash.org/repellatearumcorrupti.png?size=50x50&set=set1","sexo":"M","pais":"Czech Republic","nacimiento":"08/10/1998"},
  {"nombre":"Adriana","foto":"https://robohash.org/quirerumcommodi.png?size=50x50&set=set1","sexo":"F","pais":"Canada","nacimiento":"01/05/2002"},
  {"nombre":"Ag","foto":"https://robohash.org/teneturasequi.png?size=50x50&set=set1","sexo":"F","pais":"Portugal","nacimiento":"18/05/1971"},
  {"nombre":"Doralia","foto":"https://robohash.org/eavelaccusantium.png?size=50x50&set=set1","sexo":"F","pais":"Indonesia","nacimiento":"20/12/1968"},
  {"nombre":"Libby","foto":"https://robohash.org/estdoloremnostrum.png?size=50x50&set=set1","sexo":"F","pais":"Colombia","nacimiento":"08/11/2000"},
  {"nombre":"Catriona","foto":"https://robohash.org/autemdoloreinventore.png?size=50x50&set=set1","sexo":"F","pais":"Indonesia","nacimiento":"21/07/1953"},
  {"nombre":"Cinda","foto":"https://robohash.org/etrerumea.png?size=50x50&set=set1","sexo":"F","pais":"Tanzania","nacimiento":"07/06/1989"},
  {"nombre":"Fionnula","foto":"https://robohash.org/ametmodieaque.png?size=50x50&set=set1","sexo":"F","pais":"Eritrea","nacimiento":"17/07/1970"},
  {"nombre":"Konstantine","foto":"https://robohash.org/iustoetab.png?size=50x50&set=set1","sexo":"M","pais":"Ireland","nacimiento":"10/03/1985"},
  {"nombre":"Ogden","foto":"https://robohash.org/quidemquiest.png?size=50x50&set=set1","sexo":"M","pais":"Ecuador","nacimiento":"14/08/1987"},
  {"nombre":"Don","foto":"https://robohash.org/utdebitisadipisci.png?size=50x50&set=set1","sexo":"M","pais":"Philippines","nacimiento":"05/07/1953"},
  {"nombre":"Anthony","foto":"https://robohash.org/ineaqueporro.png?size=50x50&set=set1","sexo":"M","pais":"Spain","nacimiento":"30/08/1949"},
  {"nombre":"Alethea","foto":"https://robohash.org/verocumquenihil.png?size=50x50&set=set1","sexo":"F","pais":"Russia","nacimiento":"25/11/1943"},
  {"nombre":"Dacy","foto":"https://robohash.org/quiaasperioresrerum.png?size=50x50&set=set1","sexo":"F","pais":"Croatia","nacimiento":"08/11/1996"},
  {"nombre":"Cad","foto":"https://robohash.org/consequunturundequia.png?size=50x50&set=set1","sexo":"M","pais":"Indonesia","nacimiento":"05/05/1943"},
  {"nombre":"Feliks","foto":"https://robohash.org/suntvoluptatemnatus.png?size=50x50&set=set1","sexo":"M","pais":"Finland","nacimiento":"28/12/2001"},
  {"nombre":"Brendon","foto":"https://robohash.org/temporeitaquedeleniti.png?size=50x50&set=set1","sexo":"M","pais":"Cambodia","nacimiento":"15/08/1981"},
  {"nombre":"Johanna","foto":"https://robohash.org/exercitationemnonaliquam.png?size=50x50&set=set1","sexo":"F","pais":"Indonesia","nacimiento":"03/06/1948"},
  {"nombre":"Regina","foto":"https://robohash.org/quisinciduntpariatur.png?size=50x50&set=set1","sexo":"F","pais":"Philippines","nacimiento":"03/09/1942"},
  {"nombre":"Mariya","foto":"https://robohash.org/blanditiisinciduntvoluptates.png?size=50x50&set=set1","sexo":"F","pais":"China","nacimiento":"23/11/1953"},
  {"nombre":"Marjie","foto":"https://robohash.org/laboriosamperspiciatisa.png?size=50x50&set=set1","sexo":"F","pais":"Ghana","nacimiento":"01/12/1962"},
  {"nombre":"Elane","foto":"https://robohash.org/distinctiosedmodi.png?size=50x50&set=set1","sexo":"F","pais":"United States","nacimiento":"30/04/1986"},
  {"nombre":"Philis","foto":"https://robohash.org/quisautemea.png?size=50x50&set=set1","sexo":"F","pais":"United Kingdom","nacimiento":"27/09/2005"},
  {"nombre":"Barnett","foto":"https://robohash.org/delectuscumdeleniti.png?size=50x50&set=set1","sexo":"M","pais":"Canada","nacimiento":"18/12/1976"},
  {"nombre":"Bendicty","foto":"https://robohash.org/etaliquamut.png?size=50x50&set=set1","sexo":"M","pais":"Albania","nacimiento":"22/10/1941"},
  {"nombre":"Ezra","foto":"https://robohash.org/atquiadolor.png?size=50x50&set=set1","sexo":"M","pais":"Bolivia","nacimiento":"28/05/1954"},
  {"nombre":"Beltran","foto":"https://robohash.org/harumquisaepe.png?size=50x50&set=set1","sexo":"M","pais":"Spain","nacimiento":"10/02/1953"},
  {"nombre":"Tommie","foto":"https://robohash.org/officiaenimatque.png?size=50x50&set=set1","sexo":"M","pais":"Vietnam","nacimiento":"13/08/1950"},
  {"nombre":"Seward","foto":"https://robohash.org/velitutfugit.png?size=50x50&set=set1","sexo":"M","pais":"Philippines","nacimiento":"10/01/2008"},
  {"nombre":"Doralynne","foto":"https://robohash.org/delectusmagniprovident.png?size=50x50&set=set1","sexo":"F","pais":"Russia","nacimiento":"21/01/2001"},
  {"nombre":"Mata","foto":"https://robohash.org/expeditadolorumautem.png?size=50x50&set=set1","sexo":"M","pais":"Philippines","nacimiento":"06/03/1973"},
  {"nombre":"Dmitri","foto":"https://robohash.org/nihildoloribusquod.png?size=50x50&set=set1","sexo":"M","pais":"China","nacimiento":"26/03/1991"},
  {"nombre":"Sigismond","foto":"https://robohash.org/optioquianeque.png?size=50x50&set=set1","sexo":"M","pais":"France","nacimiento":"29/09/1960"},
  {"nombre":"Lefty","foto":"https://robohash.org/impedititaquedelectus.png?size=50x50&set=set1","sexo":"M","pais":"Ukraine","nacimiento":"10/05/1982"},
  {"nombre":"Fredericka","foto":"https://robohash.org/temporeodioaut.png?size=50x50&set=set1","sexo":"F","pais":"Ethiopia","nacimiento":"06/05/2010"},
  {"nombre":"Myrtie","foto":"https://robohash.org/facilisametnon.png?size=50x50&set=set1","sexo":"F","pais":"Indonesia","nacimiento":"12/05/1950"},
  {"nombre":"Aloysius","foto":"https://robohash.org/harumquasiquae.png?size=50x50&set=set1","sexo":"M","pais":"China","nacimiento":"17/06/2006"},
  {"nombre":"Barbe","foto":"https://robohash.org/remquasofficiis.png?size=50x50&set=set1","sexo":"F","pais":"Sweden","nacimiento":"16/05/1978"},
  {"nombre":"Johnnie","foto":"https://robohash.org/voluptasetaccusantium.png?size=50x50&set=set1","sexo":"M","pais":"Sweden","nacimiento":"08/03/1988"},
  {"nombre":"Alexine","foto":"https://robohash.org/rerumvoluptatibusa.png?size=50x50&set=set1","sexo":"F","pais":"Peru","nacimiento":"26/11/1938"}
];
